name: Deploy to AWS

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deployment script on AWS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOST}}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd PccLanjut
            docker stop icecream
            docker rm icecream
            docker pull liii1104/pcclanjut:01 
            docker run -d --name icecream -p 8080:80 liii1104/pcclanjut:01