name: Deploy to aws

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deployment script on aws
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOST}}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd PccLanjut
            docker pull liii1104/pcclanjut:01 
            docker run -itd -p 8080:80 liii1104/pcclanjut:01