name: Deploy to aws

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deployment script on aws
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.AWS_HOST}}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            cd PccLanjut
            docker image pull ${{ secrets.DOCKER_USERNAME }}/pcclanjut:01 
            docker stop liii1104/pcclanjut
            docker rm liii1104/pcclanjut
            docker run -itd --name liii1104/pcclanjut -p 8080:80 {{secrets.DOCKER_USERNAME}}/pcclanjut:01